<?php

namespace PP\AppliBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IngredientUniteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientUniteRepository extends EntityRepository
{
}
