<?php

namespace PP\AppliBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RecetteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecetteRepository extends EntityRepository
{
	public function searchRecette($recette)
	{
		$qb = $this->createQueryBuilder('r');
			
			$qb->where("r.rctTitre LIKE :recette AND r.rctStatut = :statut")
				->setParameter('recette', '%'.$recette.'%')
				->setParameter('statut', 'finale');
			
			return $qb->getQuery()->getResult();
	}
}
