<?php

namespace PP\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends EntityRepository
{
	public function searchUser($user)
	{
		$qb = $this->createQueryBuilder('u');
			
			$qb->where('u.username LIKE :user')
				->setParameter('user', '%'.$user.'%');
			
			return $qb->getQuery()->getResult();
	}
}
