pp_user_profil:
    path:     /profil
    defaults: { _controller: PPUserBundle:User:profil }

pp_user_editerProfil:
    path:    /editer
    defaults: { _controller: PPUserBundle:User:editer }

pp_user_supprimerUtilisateur:
    path:    /supprimer
    defaults: { _controller: PPUserBundle:User:supprimer }