pp_user_profil:
    path:     /profil
    defaults: { _controller: PPUserBundle:User:profil }

pp_user_editerProfil:
    path:    /editerProfil
    defaults: { _controller: PPUserBundle:User:editerProfil }