pp_appli_index:
    path:     /
    defaults: { _controller: PPAppliBundle:Appli:index }

pp_appli_recetteListe:
    path:    /recettes/{idCat}
    defaults: { _controller: PPAppliBundle:Appli:recetteListe, idCat:0 }

pp_appli_recetteDetail:
    path:    /recette/detail/{id}
    defaults: { _controller: PPAppliBundle:Appli:recetteDetail }
    requirements:
        id:    \d+

pp_appli_search:
    path:    /search
    defaults: { _controller: PPAppliBundle:Appli:search }

pp_appli_nouveautes:
    path:    /nouveautes/{page}
    defaults: { _controller: PPAppliBundle:Appli:nouveautes, page:1 }
    requirements:
        id:    \d+

pp_appli_populaire:
    path:    /populaire/{page}
    defaults: { _controller: PPAppliBundle:Appli:populaire, page: 1}
    requirements:
        id:    \d+

pp_appli_ajouterRecette:
    path:    /user/recette/ajouter
    defaults: { _controller: PPAppliBundle:Recette:ajouterRecette }

pp_appli_editRecette:
    path:    /user/recette/edit/{id}
    defaults: { _controller: PPAppliBundle:Recette:editRecette }
    requirements:
        id:    \d+

pp_appli_supprimerRecette:
    path:    /user/recette/supprimer/{id}
    defaults: { _controller: PPAppliBundle:Recette:supprimerRecette }
    requirements:
        id:    \d+

pp_appli_ajouterIngredient:
    path:    /user/recette/ingredient/ajouter
    defaults: { _controller: PPAppliBundle:Recette:ajouterIngredient }

pp_appli_ajouterUnite:
    path:    /user/recette/unite/ajouter
    defaults: { _controller: PPAppliBundle:Recette:ajouterUnite }

pp_appli_ajouterIngredientRecette:
    path:    /user/recette/ajouterIngredient
    defaults: { _controller: PPAppliBundle:Recette:ajouterIngredientRecette }