pp_appli_index:
    path:     /
    defaults: { _controller: PPAppliBundle:Appli:index }

pp_appli_recetteListe:
    path:    /recettes/{idCat}/{page}
    defaults: { _controller: PPAppliBundle:Appli:recetteListe, idCat:0, page:1 }
    requirements:
        idCat:    \d+
        page:    \d+

pp_appli_recetteDetail:
    path:    /recette/detail/{id}
    defaults: { _controller: PPAppliBundle:Appli:recetteDetail }
    requirements:
        id:    \d+

pp_appli_search:
    path:    /search/{page}
    defaults: { _controller: PPAppliBundle:Appli:search, page:1 }
    requirements:
        page:    \d+

pp_appli_nouveautes:
    path:    /nouveautes/{page}
    defaults: { _controller: PPAppliBundle:Appli:nouveautes, page:1 }
    requirements:
        page:    \d+

pp_appli_populaire:
    path:    /populaire/{page}
    defaults: { _controller: PPAppliBundle:Appli:populaire, page: 1}
    requirements:
        page:    \d+

pp_appli_ajouterRecette:
    path:    /user/recette/ajouter
    defaults: { _controller: PPAppliBundle:Recette:ajouterRecette }

pp_appli_editRecette:
    path:    /user/recette/edit/{id}
    defaults: { _controller: PPAppliBundle:Recette:editRecette }
    requirements:
        id:    \d+

pp_appli_supprimerRecette:
    path:    /user/recette/supprimer/{id}
    defaults: { _controller: PPAppliBundle:Recette:supprimerRecette }
    requirements:
        id:    \d+

pp_appli_listeIngredient:
    path:    /user/ingredient/liste
    defaults: { _controller: PPAppliBundle:Ingredient:liste }

pp_appli_ajouterIngredient:
    path:    /user/ingredient/ajouter
    defaults: { _controller: PPAppliBundle:Ingredient:ajouter }
    requirements:
        id:    \d+

pp_appli_editionIngredient:
    path:    /user/ingredient/edit/{id}
    defaults: { _controller: PPAppliBundle:Ingredient:edition }
    requirements:
        id:    \d+

pp_appli_listeUnite:
    path:    /user/unite/liste
    defaults: { _controller: PPAppliBundle:Unite:liste }

pp_appli_ajouterUnite:
    path:    /user/recette/unite/ajouter
    defaults: { _controller: PPAppliBundle:Unite:ajouter }
    requirements:
        id:    \d+

pp_appli_editionUnite:
    path:    /user/unite/edit/{id}
    defaults: { _controller: PPAppliBundle:Unite:edition }
    requirements:
        id:    \d+

pp_appli_ajouterIngredientRecette:
    path:    /user/recette/ajouterIngredient
    defaults: { _controller: PPAppliBundle:Recette:ajouterIngredientRecette }

pp_appli_menus:
    path:    /user/menu/liste
    defaults: { _controller: PPAppliBundle:Menu:liste }

pp_appli_ajouterMenu:
    path:    /user/menu/ajouter
    defaults: { _controller: PPAppliBundle:Menu:ajouter }

pp_appli_supprimerMenu:
    path:    /user/menu/supprimer/{id}
    defaults: { _controller: PPAppliBundle:Menu:supprimer }
    requirements:
        id:    \d+

pp_appli_ajouterRecetteMenu:
    path:    /user/menu/ajouterRecette/{id}
    defaults: { _controller: PPAppliBundle:Menu:ajouterRecette }
    requirements:
        id:    \d+

pp_appli_supprimerRecetteMenu:
    path:    /user/menu/{id}/supprimerRecette/{idRecette}
    defaults: { _controller: PPAppliBundle:Menu:supprimerRecette }
    requirements:
        id:    \d+
        idRecette:    \d+

pp_appli_editerRecettesMenu:
    path:    /user/menu/editerRecettes/{id}
    defaults: { _controller: PPAppliBundle:Menu:editerRecettes }
    requirements:
        id:    \d+

pp_appli_listeIngredientsMenu:
    path:    /user/menu/{id}/listeIngredient
    defaults: { _controller: PPAppliBundle:Menu:listeIngredients }
    requirements:
        id:    \d+

pp_appli_listes:
    path:    /user/liste/liste
    defaults: { _controller: PPAppliBundle:Liste:liste }

pp_appli_ajouterListe:
    path:    /user/liste/ajouter
    defaults: { _controller: PPAppliBundle:Liste:ajouter }

pp_appli_supprimerListe:
    path:    /user/liste/supprimer/{id}
    defaults: { _controller: PPAppliBundle:Liste:supprimer }
    requirements:
        id:    \d+

pp_appli_gestionIngredientsListe:
    path:    /user/liste/gestion/{id}
    defaults: { _controller: PPAppliBundle:Liste:gestion }
    requirements:
        id:    \d+

pp_appli_supprimerIngredientListe:
    path:    /user/liste/{id}/supprimerIngredient/{idIngredient}
    defaults:    { _controller: PPAppliBundle:Liste:supprimerIngredient }
    requirements:
        id:    \d+
        idIngredient:    \d+

pp_appli_recettesListe:
    path:    /user/liste/{id}/recettes
    defaults: { _controller: PPAppliBundle:Liste:recettes }
    requirements:
        id:    \d+